name: t3c-main
type: typo3
docroot: "."
php_version: "8.2"
webserver_type: apache-fpm
database:
  type: mariadb
  version: "10.11"
composer_version: "stable"
nodejs_version: "22"
timezone: Europe/Berlin
web_environment:
  - TYPO3_CONTEXT=Development
